// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: infraalerts.sql

package db

import (
	"context"
)

const getInfrastructureAlertState = `-- name: GetInfrastructureAlertState :one
SELECT value FROM infrastructure_alert_state WHERE key = $1
`

func (q *Queries) GetInfrastructureAlertState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInfrastructureAlertState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const maxInboundEventID = `-- name: MaxInboundEventID :one
SELECT CAST(COALESCE(MAX(id), 0) AS BIGINT) FROM inbound_events
`

func (q *Queries) MaxInboundEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxInboundEventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setInfrastructureAlertState = `-- name: SetInfrastructureAlertState :exec
INSERT INTO infrastructure_alert_state (key, value, updated_at) VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetInfrastructureAlertStateParams struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) SetInfrastructureAlertState(ctx context.Context, arg SetInfrastructureAlertStateParams) error {
	_, err := q.db.ExecContext(ctx, setInfrastructureAlertState, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
