// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promocodes.sql

package db

import (
	"context"
	"database/sql"
)

const claimLatePromoRefund = `-- name: ClaimLatePromoRefund :execrows
UPDATE promo_redemptions SET refund_started_at=$1 WHERE id=$2
  AND (status='released' OR (status='reserved' AND expires_at IS NOT NULL AND expires_at<=$3))
  AND (refund_started_at IS NULL OR refund_started_at<=$4)
`

type ClaimLatePromoRefundParams struct {
	RefundStartedAt sql.NullInt64
	ID              int64
	Now             sql.NullInt64
	RetryAfter      sql.NullInt64
}

func (q *Queries) ClaimLatePromoRefund(ctx context.Context, arg ClaimLatePromoRefundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimLatePromoRefund,
		arg.RefundStartedAt,
		arg.ID,
		arg.Now,
		arg.RetryAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDisabledPromoPools = `-- name: ClearDisabledPromoPools :exec
UPDATE promo_codes SET pool_id=NULL WHERE pool_id=$1 AND (enabled=0 OR deleted=1)
`

func (q *Queries) ClearDisabledPromoPools(ctx context.Context, poolID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, clearDisabledPromoPools, poolID)
	return err
}

const countActivePromoCodes = `-- name: CountActivePromoCodes :one
SELECT COUNT(*) FROM promo_codes WHERE deleted=0 AND enabled=1
  AND (starts_at IS NULL OR starts_at<=$1) AND (ends_at IS NULL OR ends_at>$1)
  AND (max_uses IS NULL OR used_count<max_uses)
`

func (q *Queries) CountActivePromoCodes(ctx context.Context, now sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePromoCodes, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledPromoCodesForPool = `-- name: CountEnabledPromoCodesForPool :one
SELECT COUNT(*) FROM promo_codes WHERE pool_id=$1 AND enabled=1 AND deleted=0
`

func (q *Queries) CountEnabledPromoCodesForPool(ctx context.Context, poolID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledPromoCodesForPool, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoCodes = `-- name: CountPromoCodes :one
SELECT COUNT(*) FROM promo_codes WHERE deleted = 0
`

func (q *Queries) CountPromoCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoRedemptions = `-- name: CountPromoRedemptions :one
SELECT COUNT(*) FROM promo_redemptions
`

func (q *Queries) CountPromoRedemptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoRedemptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoUser = `-- name: CountPromoUser :one
SELECT COUNT(*) FROM promo_redemptions WHERE promo_id=$1 AND (tg_id=$2 OR user_id=$3) AND status IN ('reserved','applied')
`

type CountPromoUserParams struct {
	PromoID int64
	TgID    int64
	UserID  sql.NullInt64
}

func (q *Queries) CountPromoUser(ctx context.Context, arg CountPromoUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoUser, arg.PromoID, arg.TgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserPaidPayments = `-- name: CountUserPaidPayments :one
SELECT COUNT(*) FROM payments WHERE tg_id=$1 AND status IN ('paid','applied')
`

func (q *Queries) CountUserPaidPayments(ctx context.Context, tgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPaidPayments, tgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes
(code,name,description,type,value,currency,starts_at,ends_at,max_uses,per_user_limit,discount_ttl,min_order,max_discount,tariff_ids,pool_id,first_purchase_only,new_users_only,enabled,deleted,created_at,created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,0,$19,$20) RETURNING id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by
`

type CreatePromoCodeParams struct {
	Code              string
	Name              string
	Description       string
	Type              string
	Value             int64
	Currency          string
	StartsAt          sql.NullInt64
	EndsAt            sql.NullInt64
	MaxUses           sql.NullInt64
	PerUserLimit      int64
	DiscountTtl       int64
	MinOrder          int64
	MaxDiscount       int64
	TariffIds         string
	PoolID            sql.NullInt64
	FirstPurchaseOnly int64
	NewUsersOnly      int64
	Enabled           int64
	CreatedAt         int64
	CreatedBy         sql.NullInt64
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, createPromoCode,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Value,
		arg.Currency,
		arg.StartsAt,
		arg.EndsAt,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.DiscountTtl,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.TariffIds,
		arg.PoolID,
		arg.FirstPurchaseOnly,
		arg.NewUsersOnly,
		arg.Enabled,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createPromoRedemption = `-- name: CreatePromoRedemption :one
INSERT INTO promo_redemptions
(promo_id,user_id,tg_id,payment_id,status,redeemed_at,expires_at,days,bytes,discount_amount,original_amount,final_amount,currency,note)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note
`

type CreatePromoRedemptionParams struct {
	PromoID        int64
	UserID         sql.NullInt64
	TgID           int64
	PaymentID      sql.NullInt64
	Status         string
	RedeemedAt     int64
	ExpiresAt      sql.NullInt64
	Days           int64
	Bytes          int64
	DiscountAmount int64
	OriginalAmount int64
	FinalAmount    int64
	Currency       string
	Note           string
}

func (q *Queries) CreatePromoRedemption(ctx context.Context, arg CreatePromoRedemptionParams) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, createPromoRedemption,
		arg.PromoID,
		arg.UserID,
		arg.TgID,
		arg.PaymentID,
		arg.Status,
		arg.RedeemedAt,
		arg.ExpiresAt,
		arg.Days,
		arg.Bytes,
		arg.DiscountAmount,
		arg.OriginalAmount,
		arg.FinalAmount,
		arg.Currency,
		arg.Note,
	)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const decrementPromoUse = `-- name: DecrementPromoUse :execrows
UPDATE promo_codes SET used_count=CASE WHEN used_count>0 THEN used_count-1 ELSE 0 END WHERE id=$1
`

func (q *Queries) DecrementPromoUse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementPromoUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePromoCode = `-- name: DeletePromoCode :execrows
UPDATE promo_codes SET deleted=1, enabled=0, pool_id=NULL WHERE id=$1 AND deleted=0
`

func (q *Queries) DeletePromoCode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePromoCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPromoCode = `-- name: GetPromoCode :one
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE id = $1
`

func (q *Queries) GetPromoCode(ctx context.Context, id int64) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, getPromoCode, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE code = $1 AND deleted=0
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPromoRedemption = `-- name: GetPromoRedemption :one
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions WHERE id=$1
`

func (q *Queries) GetPromoRedemption(ctx context.Context, id int64) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, getPromoRedemption, id)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const getPromoRedemptionByPayment = `-- name: GetPromoRedemptionByPayment :one
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions WHERE payment_id=$1
`

func (q *Queries) GetPromoRedemptionByPayment(ctx context.Context, paymentID sql.NullInt64) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, getPromoRedemptionByPayment, paymentID)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const incrementPromoUse = `-- name: IncrementPromoUse :execrows
UPDATE promo_codes SET used_count=used_count+1 WHERE id=$1 AND (max_uses IS NULL OR used_count < max_uses) AND deleted=0 AND enabled=1
`

func (q *Queries) IncrementPromoUse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementPromoUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExpiredPromoPayments = `-- name: ListExpiredPromoPayments :many
SELECT DISTINCT p.id FROM payments p JOIN promo_redemptions r ON r.payment_id=p.id WHERE ((p.status='expired' AND p.created_at < $1) OR (r.expires_at IS NOT NULL AND r.expires_at<=$1 AND p.status IN ('pending','expired','failed','refunded'))) AND r.status='reserved'
`

func (q *Queries) ListExpiredPromoPayments(ctx context.Context, before int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPromoPayments, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatePromoRefunds = `-- name: ListLatePromoRefunds :many
SELECT id FROM payments WHERE error='promo_late_refund_failed' AND status IN ('pending','expired','paid','failed') ORDER BY id
`

func (q *Queries) ListLatePromoRefunds(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listLatePromoRefunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE deleted = 0 ORDER BY id DESC LIMIT CAST($2 AS BIGINT) OFFSET CAST($1 AS BIGINT)
`

type ListPromoCodesParams struct {
	RowOffset int64
	Lim       int64
}

func (q *Queries) ListPromoCodes(ctx context.Context, arg ListPromoCodesParams) ([]PromoCode, error) {
	rows, err := q.db.QueryContext(ctx, listPromoCodes, arg.RowOffset, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoCode{}
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Value,
			&i.Currency,
			&i.StartsAt,
			&i.EndsAt,
			&i.MaxUses,
			&i.UsedCount,
			&i.PerUserLimit,
			&i.DiscountTtl,
			&i.MinOrder,
			&i.MaxDiscount,
			&i.TariffIds,
			&i.PoolID,
			&i.FirstPurchaseOnly,
			&i.NewUsersOnly,
			&i.Enabled,
			&i.Deleted,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoRedemptionsByTgWithCode = `-- name: ListPromoRedemptionsByTgWithCode :many
SELECT r.id, r.promo_id, r.user_id, r.tg_id, r.payment_id, r.status, r.refund_started_at, r.redeemed_at, r.expires_at, r.days, r.bytes, r.discount_amount, r.original_amount, r.final_amount, r.currency, r.note, c.code FROM promo_redemptions r JOIN promo_codes c ON c.id=r.promo_id
WHERE r.tg_id=$1 AND r.status='applied' ORDER BY r.id DESC LIMIT CAST($2 AS BIGINT)
`

type ListPromoRedemptionsByTgWithCodeParams struct {
	TgID int64
	Lim  int64
}

type ListPromoRedemptionsByTgWithCodeRow struct {
	ID              int64
	PromoID         int64
	UserID          sql.NullInt64
	TgID            int64
	PaymentID       sql.NullInt64
	Status          string
	RefundStartedAt sql.NullInt64
	RedeemedAt      int64
	ExpiresAt       sql.NullInt64
	Days            int64
	Bytes           int64
	DiscountAmount  int64
	OriginalAmount  int64
	FinalAmount     int64
	Currency        string
	Note            string
	Code            string
}

func (q *Queries) ListPromoRedemptionsByTgWithCode(ctx context.Context, arg ListPromoRedemptionsByTgWithCodeParams) ([]ListPromoRedemptionsByTgWithCodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPromoRedemptionsByTgWithCode, arg.TgID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromoRedemptionsByTgWithCodeRow{}
	for rows.Next() {
		var i ListPromoRedemptionsByTgWithCodeRow
		if err := rows.Scan(
			&i.ID,
			&i.PromoID,
			&i.UserID,
			&i.TgID,
			&i.PaymentID,
			&i.Status,
			&i.RefundStartedAt,
			&i.RedeemedAt,
			&i.ExpiresAt,
			&i.Days,
			&i.Bytes,
			&i.DiscountAmount,
			&i.OriginalAmount,
			&i.FinalAmount,
			&i.Currency,
			&i.Note,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoRedemptionsWithCode = `-- name: ListPromoRedemptionsWithCode :many
SELECT r.id, r.promo_id, r.user_id, r.tg_id, r.payment_id, r.status, r.refund_started_at, r.redeemed_at, r.expires_at, r.days, r.bytes, r.discount_amount, r.original_amount, r.final_amount, r.currency, r.note, c.code FROM promo_redemptions r JOIN promo_codes c ON c.id=r.promo_id
ORDER BY r.id DESC LIMIT CAST($2 AS BIGINT) OFFSET CAST($1 AS BIGINT)
`

type ListPromoRedemptionsWithCodeParams struct {
	RowOffset int64
	Lim       int64
}

type ListPromoRedemptionsWithCodeRow struct {
	ID              int64
	PromoID         int64
	UserID          sql.NullInt64
	TgID            int64
	PaymentID       sql.NullInt64
	Status          string
	RefundStartedAt sql.NullInt64
	RedeemedAt      int64
	ExpiresAt       sql.NullInt64
	Days            int64
	Bytes           int64
	DiscountAmount  int64
	OriginalAmount  int64
	FinalAmount     int64
	Currency        string
	Note            string
	Code            string
}

func (q *Queries) ListPromoRedemptionsWithCode(ctx context.Context, arg ListPromoRedemptionsWithCodeParams) ([]ListPromoRedemptionsWithCodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPromoRedemptionsWithCode, arg.RowOffset, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromoRedemptionsWithCodeRow{}
	for rows.Next() {
		var i ListPromoRedemptionsWithCodeRow
		if err := rows.Scan(
			&i.ID,
			&i.PromoID,
			&i.UserID,
			&i.TgID,
			&i.PaymentID,
			&i.Status,
			&i.RefundStartedAt,
			&i.RedeemedAt,
			&i.ExpiresAt,
			&i.Days,
			&i.Bytes,
			&i.DiscountAmount,
			&i.OriginalAmount,
			&i.FinalAmount,
			&i.Currency,
			&i.Note,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPromoApplied = `-- name: MarkPromoApplied :execrows
UPDATE promo_redemptions SET status='applied', user_id=COALESCE($1,user_id) WHERE id=$2 AND status IN ('reserved','released')
`

type MarkPromoAppliedParams struct {
	UserID sql.NullInt64
	ID     int64
}

func (q *Queries) MarkPromoApplied(ctx context.Context, arg MarkPromoAppliedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPromoApplied, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promoStats = `-- name: PromoStats :one
SELECT COUNT(CASE WHEN status='applied' THEN 1 END) AS successful_activations, CAST(COALESCE(SUM(CASE WHEN status='applied' THEN days ELSE 0 END),0) AS BIGINT) AS bonus_days, CAST(COALESCE(SUM(CASE WHEN status='applied' THEN bytes ELSE 0 END),0) AS BIGINT) AS bonus_bytes, CAST(COALESCE(SUM(CASE WHEN status='applied' THEN discount_amount ELSE 0 END),0) AS BIGINT) AS discount_amount, CAST(COALESCE(SUM(CASE WHEN status='applied' AND payment_id IS NOT NULL THEN 1 ELSE 0 END),0) AS BIGINT) AS discount_orders FROM promo_redemptions
`

type PromoStatsRow struct {
	SuccessfulActivations int64
	BonusDays             int64
	BonusBytes            int64
	DiscountAmount        int64
	DiscountOrders        int64
}

func (q *Queries) PromoStats(ctx context.Context) (PromoStatsRow, error) {
	row := q.db.QueryRowContext(ctx, promoStats)
	var i PromoStatsRow
	err := row.Scan(
		&i.SuccessfulActivations,
		&i.BonusDays,
		&i.BonusBytes,
		&i.DiscountAmount,
		&i.DiscountOrders,
	)
	return i, err
}

const releaseExpiredPromoRedemption = `-- name: ReleaseExpiredPromoRedemption :execrows
UPDATE promo_redemptions SET status='released' WHERE promo_redemptions.id=$1 AND promo_redemptions.status='reserved' AND (promo_redemptions.expires_at IS NOT NULL AND promo_redemptions.expires_at<=$2 AND EXISTS (SELECT 1 FROM payments p WHERE p.id=promo_redemptions.payment_id AND p.status IN ('pending','expired','failed','refunded')) OR EXISTS (SELECT 1 FROM payments p WHERE p.id=promo_redemptions.payment_id AND p.status IN ('failed','expired','refunded') AND p.created_at<$2))
`

type ReleaseExpiredPromoRedemptionParams struct {
	ID     int64
	Before sql.NullInt64
}

func (q *Queries) ReleaseExpiredPromoRedemption(ctx context.Context, arg ReleaseExpiredPromoRedemptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseExpiredPromoRedemption, arg.ID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseLatePromoRefundClaim = `-- name: ReleaseLatePromoRefundClaim :exec
UPDATE promo_redemptions SET refund_started_at=NULL WHERE payment_id=$1
`

func (q *Queries) ReleaseLatePromoRefundClaim(ctx context.Context, paymentID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, releaseLatePromoRefundClaim, paymentID)
	return err
}

const releasePromoRedemptionForClosedPayment = `-- name: ReleasePromoRedemptionForClosedPayment :execrows
UPDATE promo_redemptions SET status='released'
WHERE promo_redemptions.id=$1 AND promo_redemptions.status='reserved' AND EXISTS (
  SELECT 1 FROM payments p WHERE p.id=promo_redemptions.payment_id AND p.status IN ('failed','expired','refunded')
)
`

func (q *Queries) ReleasePromoRedemptionForClosedPayment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, releasePromoRedemptionForClosedPayment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restorePromoUse = `-- name: RestorePromoUse :exec
UPDATE promo_codes SET used_count=used_count+1 WHERE id=$1
`

func (q *Queries) RestorePromoUse(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restorePromoUse, id)
	return err
}

const setPromoEnabled = `-- name: SetPromoEnabled :execrows
UPDATE promo_codes SET enabled=$1 WHERE id=$2 AND deleted=0
`

type SetPromoEnabledParams struct {
	Enabled int64
	ID      int64
}

func (q *Queries) SetPromoEnabled(ctx context.Context, arg SetPromoEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPromoEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePromoCode = `-- name: UpdatePromoCode :one
UPDATE promo_codes SET
code=$1,name=$2,description=$3,type=$4,value=$5,currency=$6,starts_at=$7,ends_at=$8,max_uses=$9,per_user_limit=$10,discount_ttl=$11,min_order=$12,max_discount=$13,tariff_ids=$14,pool_id=$15,first_purchase_only=$16,new_users_only=$17,enabled=$18 WHERE id=$19 AND deleted=0 RETURNING id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by
`

type UpdatePromoCodeParams struct {
	Code              string
	Name              string
	Description       string
	Type              string
	Value             int64
	Currency          string
	StartsAt          sql.NullInt64
	EndsAt            sql.NullInt64
	MaxUses           sql.NullInt64
	PerUserLimit      int64
	DiscountTtl       int64
	MinOrder          int64
	MaxDiscount       int64
	TariffIds         string
	PoolID            sql.NullInt64
	FirstPurchaseOnly int64
	NewUsersOnly      int64
	Enabled           int64
	ID                int64
}

func (q *Queries) UpdatePromoCode(ctx context.Context, arg UpdatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, updatePromoCode,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Value,
		arg.Currency,
		arg.StartsAt,
		arg.EndsAt,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.DiscountTtl,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.TariffIds,
		arg.PoolID,
		arg.FirstPurchaseOnly,
		arg.NewUsersOnly,
		arg.Enabled,
		arg.ID,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
