-- +goose Up
-- PostgreSQL baseline. Legacy SQLite migrations are used only by the importer.
CREATE TABLE admins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       TEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  totp_secret    TEXT,
  recovery_codes TEXT,
  created_at     BIGINT NOT NULL,
  last_login_at  BIGINT
);

CREATE TABLE audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          BIGINT NOT NULL,
  admin_id    BIGINT,
  action      TEXT NOT NULL,
  target_type TEXT,
  target_id   TEXT,
  ip          TEXT,
  details     TEXT
);

CREATE TABLE node_state (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE nodes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
  name        TEXT NOT NULL DEFAULT '',
  address     TEXT NOT NULL DEFAULT '',
  public_host TEXT NOT NULL DEFAULT '',
  domain      TEXT NOT NULL DEFAULT '',
  cert_sha256 TEXT NOT NULL DEFAULT '',
  enabled     BIGINT NOT NULL DEFAULT 1,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL,
  public_name TEXT NOT NULL DEFAULT ''
);

CREATE TABLE infrastructure_alert_state (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE slot_counter (
  id   BIGINT PRIMARY KEY CHECK (id = 1),
  last BIGINT NOT NULL
);

CREATE TABLE slots (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  uuid       TEXT NOT NULL UNIQUE,
  secret     TEXT NOT NULL,
  state      TEXT NOT NULL CHECK (state IN ('free', 'assigned', 'burned')),
  created_at BIGINT NOT NULL,
  burned_at  BIGINT
);

CREATE TABLE tariffs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  traffic_limit  BIGINT,
  duration_days  BIGINT NOT NULL,
  device_limit   BIGINT,
  reset_strategy TEXT NOT NULL DEFAULT 'none' CHECK (reset_strategy IN ('none', 'month_start', 'period')),
  price_label    TEXT NOT NULL DEFAULT '',
  sort           BIGINT NOT NULL DEFAULT 0,
  archived       BIGINT NOT NULL DEFAULT 0,
  created_at     BIGINT NOT NULL
, billing_day BIGINT, price_stars BIGINT, price_rub BIGINT, on_sale BIGINT NOT NULL DEFAULT 0);

CREATE TABLE tg_chats (
  tg_id       BIGINT PRIMARY KEY,
  username    TEXT NOT NULL DEFAULT '',
  first_name  TEXT NOT NULL DEFAULT '',
  menu_msg_id BIGINT NOT NULL DEFAULT 0, -- the bot's menu message: edited in place, replaced on new input
  current     BIGINT NOT NULL DEFAULT 0, -- the subscription shown when several are linked
  blocked     BIGINT NOT NULL DEFAULT 0, -- the user blocked the bot: nothing is sent
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL
);

CREATE TABLE traffic_pools (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL
);

CREATE TABLE api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  prefix       TEXT NOT NULL,        -- the key's first characters, to tell keys apart
  hash         TEXT NOT NULL UNIQUE, -- hex SHA-256 of the key
  scope        TEXT NOT NULL CHECK (scope IN ('read', 'full')),
  created_at   BIGINT NOT NULL,
  expires_at   BIGINT,              -- NULL: until revoked
  last_used_at BIGINT,
  last_ip      TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "inbounds" (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id      BIGINT NOT NULL DEFAULT 1 REFERENCES nodes(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  preset       TEXT NOT NULL,
  port         TEXT NOT NULL,
  enabled      BIGINT NOT NULL DEFAULT 1,
  settings     TEXT NOT NULL,
  created_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL,
  display_name TEXT NOT NULL DEFAULT '',
  config       TEXT NOT NULL DEFAULT '', auto_port BIGINT NOT NULL DEFAULT 1, auto_sni BIGINT NOT NULL DEFAULT 1, outbound TEXT NOT NULL DEFAULT 'direct' CHECK (outbound IN ('direct', 'warp')), exit_node_id BIGINT REFERENCES nodes(id) ON DELETE SET NULL, pool_id BIGINT REFERENCES traffic_pools(id) ON DELETE SET NULL, listen TEXT NOT NULL DEFAULT '',
  UNIQUE (node_id, name)
);

CREATE TABLE node_relays (
  node_id      BIGINT PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
  port         TEXT NOT NULL,
  config       TEXT NOT NULL,                                    -- VLESS REALITY template (YAML)
  outbound     TEXT NOT NULL DEFAULT 'direct' CHECK (outbound IN ('direct', 'warp')),
  exit_node_id BIGINT REFERENCES nodes(id) ON DELETE SET NULL,  -- set: the relay goes on to that node
  created_at   BIGINT NOT NULL
);

CREATE TABLE node_warp (
  node_id         BIGINT PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
  enabled         BIGINT NOT NULL DEFAULT 1,
  source          TEXT NOT NULL CHECK (source IN ('register', 'import')),
  private_key     TEXT NOT NULL,                -- never leaves the panel but to its node
  peer_public_key TEXT NOT NULL,
  endpoint        TEXT NOT NULL,                -- host:port
  ipv4            TEXT NOT NULL,
  ipv6            TEXT NOT NULL DEFAULT '',
  reserved        TEXT NOT NULL DEFAULT '',     -- base64 of WARP's 3-byte client id
  mtu             BIGINT NOT NULL DEFAULT 1280,
  account_id      TEXT NOT NULL DEFAULT '',     -- the Cloudflare registration, for a WARP+ key
  account_token   TEXT NOT NULL DEFAULT '',
  plus            BIGINT NOT NULL DEFAULT 0,
  routes          TEXT NOT NULL DEFAULT '[]',   -- JSON: domain suffixes and networks through WARP
  created_at      BIGINT NOT NULL,
  updated_at      BIGINT NOT NULL
);

CREATE TABLE relay_users (
  exit_node_id BIGINT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  src_node_id  BIGINT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  uuid         TEXT NOT NULL,
  PRIMARY KEY (exit_node_id, src_node_id)
);

CREATE TABLE sessions (
  id_hash      TEXT PRIMARY KEY,
  admin_id     BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  csrf_token   TEXT NOT NULL,
  created_at   BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  expires_at   BIGINT NOT NULL,
  ip           TEXT NOT NULL,
  user_agent   TEXT NOT NULL
);

CREATE TABLE tariff_pools (
  tariff_id     BIGINT NOT NULL REFERENCES tariffs(id) ON DELETE CASCADE,
  pool_id       BIGINT NOT NULL REFERENCES traffic_pools(id) ON DELETE CASCADE,
  traffic_limit BIGINT NOT NULL, -- bytes
  PRIMARY KEY (tariff_id, pool_id)
);

CREATE TABLE traffic_packages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  bytes       BIGINT NOT NULL CHECK (bytes > 0),
  pool_id     BIGINT REFERENCES traffic_pools(id) ON DELETE CASCADE, -- NULL: the main traffic
  lifetime    TEXT NOT NULL CHECK (lifetime IN ('used', 'period', 'days')),
  days        BIGINT NOT NULL DEFAULT 0,                             -- lifetime 'days': from the purchase
  price_stars BIGINT,                                                -- NULL: not sold for Stars
  price_rub   BIGINT,                                                -- kopecks; NULL: not sold for rubles
  on_sale     BIGINT NOT NULL DEFAULT 0,
  sort        BIGINT NOT NULL DEFAULT 0,
  archived    BIGINT NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL,
  CHECK (lifetime <> 'days' OR days BETWEEN 1 AND 3650)
);

CREATE TABLE users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  contact        TEXT NOT NULL DEFAULT '',
  note           TEXT NOT NULL DEFAULT '',
  tags           TEXT NOT NULL DEFAULT '[]',
  status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  tariff_id      BIGINT REFERENCES tariffs(id) ON DELETE SET NULL,
  traffic_limit  BIGINT,
  device_limit   BIGINT,
  reset_strategy TEXT NOT NULL DEFAULT 'none' CHECK (reset_strategy IN ('none', 'month_start', 'period')),
  period_days    BIGINT NOT NULL DEFAULT 0,
  period_start   BIGINT NOT NULL,
  used_up        BIGINT NOT NULL DEFAULT 0,
  used_down      BIGINT NOT NULL DEFAULT 0,
  total_up       BIGINT NOT NULL DEFAULT 0,
  total_down     BIGINT NOT NULL DEFAULT 0,
  expires_at     BIGINT,
  inbounds       TEXT,
  sub_token      TEXT NOT NULL UNIQUE,
  slot_id        BIGINT UNIQUE REFERENCES slots(id),
  online_at      BIGINT,
  created_at     BIGINT NOT NULL,
  updated_at     BIGINT NOT NULL
, billing_day BIGINT, unbound_at BIGINT NOT NULL DEFAULT 0);

CREATE TABLE bound_devices (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hwid       TEXT NOT NULL,
  slot_id    BIGINT NOT NULL REFERENCES slots(id),
  os         TEXT NOT NULL DEFAULT '',
  os_version TEXT NOT NULL DEFAULT '',
  model      TEXT NOT NULL DEFAULT '',
  app        TEXT NOT NULL DEFAULT '',
  last_ip    TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  last_seen  BIGINT NOT NULL,
  UNIQUE (user_id, hwid)
);

CREATE TABLE devices (
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ip         TEXT NOT NULL,
  first_seen BIGINT NOT NULL,
  last_seen  BIGINT NOT NULL,
  PRIMARY KEY (user_id, ip)
);

CREATE TABLE inbound_events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inbound_id BIGINT NOT NULL REFERENCES inbounds(id) ON DELETE CASCADE,
  node_id    BIGINT NOT NULL,
  kind       TEXT NOT NULL,             -- port | sni
  network    TEXT NOT NULL DEFAULT '',  -- tcp | udp, for kind = port
  old_value  TEXT NOT NULL,
  new_value  TEXT NOT NULL,
  reason     TEXT NOT NULL,             -- blocked | target_down | still_blocked
  created_at BIGINT NOT NULL
);

CREATE TABLE inbound_reach (
  slot       TEXT NOT NULL,
  inbound_id BIGINT NOT NULL REFERENCES inbounds(id) ON DELETE CASCADE,
  at         BIGINT NOT NULL,
  PRIMARY KEY (slot, inbound_id)
);

CREATE TABLE "payments" (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider    TEXT NOT NULL CHECK (provider IN ('stars', 'yookassa', 'cryptobot') OR provider LIKE 'addon:%'),
  payload     TEXT NOT NULL UNIQUE,
  external_id TEXT,
  tg_id       BIGINT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('new', 'renew', 'package')),
  user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
  tariff_id   BIGINT REFERENCES tariffs(id),                         -- new and renew
  package_id  BIGINT REFERENCES traffic_packages(id) ON DELETE SET NULL, -- package
  tariff_name TEXT NOT NULL,                                          -- the tariff's or package's name as bought
  amount      BIGINT NOT NULL,
  currency    TEXT NOT NULL CHECK (currency IN ('XTR', 'RUB')),
  status      TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'applied', 'expired', 'failed', 'refunded')),
  error       TEXT NOT NULL DEFAULT '',
  pay_url     TEXT NOT NULL DEFAULT '',
  created_at  BIGINT NOT NULL,
  paid_at     BIGINT,
  applied_at  BIGINT,
  refunded_at BIGINT,
  CHECK (kind = 'package' OR tariff_id IS NOT NULL)
);

CREATE TABLE sub_fetches (
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ip         TEXT NOT NULL,
  fetched_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, ip)
);

CREATE TABLE tg_links (
  user_id    BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, -- one owner per subscription
  tg_id      BIGINT NOT NULL,                                          -- Telegram user id (= private chat id)
  created_at BIGINT NOT NULL
);

CREATE TABLE tg_notices (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind    TEXT NOT NULL,    -- expire_3d | expire_1d | expired | traffic_90 | traffic_100
  period  BIGINT NOT NULL, -- the expiry or traffic period the notice is about
  sent_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, kind, period)
);

CREATE TABLE traffic_daily (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day     BIGINT NOT NULL,
  up      BIGINT NOT NULL DEFAULT 0,
  down    BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, day)
);

CREATE TABLE traffic_hourly (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hour    BIGINT NOT NULL,
  up      BIGINT NOT NULL DEFAULT 0,
  down    BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, hour)
);

CREATE TABLE user_pools (
  user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pool_id       BIGINT NOT NULL REFERENCES traffic_pools(id) ON DELETE CASCADE,
  traffic_limit BIGINT,
  used_up       BIGINT NOT NULL DEFAULT 0,
  used_down     BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, pool_id)
);

CREATE TABLE traffic_grants (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pool_id    BIGINT REFERENCES traffic_pools(id) ON DELETE CASCADE, -- NULL: the main traffic
  bytes      BIGINT NOT NULL CHECK (bytes > 0),
  remaining  BIGINT NOT NULL CHECK (remaining BETWEEN 0 AND bytes),
  lifetime   TEXT NOT NULL CHECK (lifetime IN ('used', 'period', 'days')),
  expires_at BIGINT,
  source     TEXT NOT NULL CHECK (source IN ('purchase', 'admin')),
  payment_id BIGINT UNIQUE REFERENCES payments(id) ON DELETE SET NULL, -- one grant per payment
  package_id BIGINT REFERENCES traffic_packages(id) ON DELETE SET NULL,
  note       TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE INDEX audit_log_ts ON audit_log(ts);

CREATE INDEX bound_devices_slot ON bound_devices(slot_id);

CREATE INDEX devices_last_seen ON devices(last_seen);

CREATE INDEX inbound_events_inbound ON inbound_events(inbound_id, id);

CREATE UNIQUE INDEX payments_external ON payments(provider, external_id) WHERE external_id IS NOT NULL;

CREATE INDEX payments_status ON payments(status, created_at);

CREATE INDEX payments_user ON payments(user_id);

CREATE INDEX sessions_admin ON sessions(admin_id);

CREATE INDEX slots_state ON slots(state);

CREATE INDEX tg_links_tg ON tg_links(tg_id);

CREATE INDEX traffic_daily_day ON traffic_daily(day);

CREATE INDEX traffic_grants_user ON traffic_grants(user_id, pool_id);

CREATE INDEX traffic_hourly_hour ON traffic_hourly(hour);

CREATE INDEX users_expires ON users(expires_at);

CREATE INDEX users_status ON users(status);

CREATE TABLE prototip_sqlite_import (id BIGINT PRIMARY KEY CHECK (id = 1), report TEXT NOT NULL);

-- +goose Down
DROP TABLE infrastructure_alert_state;
DROP TABLE prototip_sqlite_import;
DROP TABLE traffic_grants;
DROP TABLE user_pools;
DROP TABLE traffic_hourly;
DROP TABLE traffic_daily;
DROP TABLE tg_notices;
DROP TABLE tg_links;
DROP TABLE sub_fetches;
DROP TABLE payments;
DROP TABLE inbound_reach;
DROP TABLE inbound_events;
DROP TABLE devices;
DROP TABLE bound_devices;
DROP TABLE users;
DROP TABLE traffic_packages;
DROP TABLE tariff_pools;
DROP TABLE sessions;
DROP TABLE relay_users;
DROP TABLE node_warp;
DROP TABLE node_relays;
DROP TABLE inbounds;
DROP TABLE api_keys;
DROP TABLE traffic_pools;
DROP TABLE tg_chats;
DROP TABLE tariffs;
DROP TABLE slots;
DROP TABLE slot_counter;
DROP TABLE settings;
DROP TABLE nodes;
DROP TABLE node_state;
DROP TABLE audit_log;
DROP TABLE admins;
